# Generated by Django 3.1.6 on 2021-02-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('AG', 'Agriculture'), ('HC', 'Handicraft'), ('RL', 'Religious'), ('FD', 'Food'), ('MD', 'Manufactured')], max_length=2)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.URLField()),
                ('origin', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
