# Generated by Django 3.1.6 on 2021-04-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='no', max_length=150),
            preserve_default=False,
        ),
    ]
